__title__ = 'bsi_sentiment'
__author__ = 'Elio Scarci, Kasra Zamanian, Pietro Dominietto, Stefano Cortinovis'
__email__ = 'scortino@pm.me'
__url__ = 'https://github.com/scortino/bsi-sentiment'
__version__ = '0.0.1'